package WelthSpring;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;

public class NewTest {

    static WebDriver driver;

    @BeforeMethod
    public void browserlaunch() {
        WebDriverManager.chromedriver().setup();
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
       
    }

    @Test
    public void loginpage() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("APPALARAJU VENKATA RAMANA RAO");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage2() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("DEEPAK KUMAR SINHA");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage3() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("DEEPAK MANHORLAL CHOPRA");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage4() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("GAUTAM KHANNA");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage5() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("KANTA C PANJWANI");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage6() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("LAKSHMI RATNAPARKHE");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage7() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("NANDINI MUKHERJEE");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage8() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("NEPUCHAPUR TEA COMPANY LIMITED");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage9() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("PRADYUMNA AGRAWAL");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage10() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("RAHIM EBRAHIM VAYALAKAD");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage11() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("PRATUL KUMAR SINGH");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage12() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("PRAVEER KUMAR THAKUR");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage13() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("PREETI AGRAWAL");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage14() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("RANJIT SINGH YADAV");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage15() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("RUPAK AGARWAL");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage16() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("SAILESH VENKATESAN");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage17() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("SOUMITRA PANDEY");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage18() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("SUJATHA V");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage19() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("SUMITA BANERJI");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage20() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("VINOD KUMAR THAKUR");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
    @Test
    public void loginpage21() throws InterruptedException {
    	 driver.get("https://wealthspring.my-portfolio.co.in/app/#/login");
         WebElement username = driver.findElement(By.xpath("//input[@name='email']"));
         username.sendKeys("WealthsAdmin");
         WebElement password = driver.findElement(By.xpath("//input[@name='password']"));
         password.sendKeys("aditya90");
         WebElement loginbutton = driver.findElement(By.xpath("//input[@type='submit']"));
         loginbutton.click();
        WebElement ClientSearch = driver.findElement(By.xpath("//input[@id='selectInput']"));
        ClientSearch.sendKeys("VIVEK JAGDISH PRASAD");
        Thread.sleep(1000);
        ClientSearch.sendKeys(Keys.ENTER);
        Thread.sleep(1000);
        WebElement report = driver.findElement(By.xpath("//a[text()='Go to Report']"));
        report.click();
        Thread.sleep(3000);
        String child = driver.getWindowHandle();
        Set<String> Parent = driver.getWindowHandles();
        List<String> list = new ArrayList<String>();
        list.addAll(Parent);
        driver.switchTo().window(list.get(1));
        Thread.sleep(1000);
        WebElement excel_button = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        excel_button.click();
        Thread.sleep(1000);
        WebElement client_wise = driver.findElement(By.xpath("(//span[@class='radioDot'])[9]"));
        client_wise.click();
        Thread.sleep(1000);
        JavascriptExecutor je = (JavascriptExecutor) driver;
        je.executeScript("window.scrollBy(0,300)");
        Thread.sleep(1000);
        WebElement apply_button = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button.click();
        Thread.sleep(1000);
        WebElement Portfolio_Performance = driver.findElement(By.xpath("//a[text()='Portfolio Performance']"));
        Portfolio_Performance.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        Thread.sleep(1000);
        WebElement Excel2 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,300)");
        WebElement apply_button2 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button2.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,-500)");
        WebElement Capital_Gain_Realized = driver.findElement(By.xpath("//a[text()='Capital Gain Realized']"));
        Capital_Gain_Realized.click();
        Thread.sleep(1000);
        WebElement Excel3 = driver.findElement(By.xpath("(//span[@class='radioDot'])[3]"));
        Excel3.click();
        Thread.sleep(1000);
        je.executeScript("window.scrollBy(0,200)");
        Thread.sleep(1000);
        WebElement apply_button3 = driver.findElement(By.xpath("//button[text()='Apply']"));
        apply_button3.click();
        Thread.sleep(2000);
       // driver.switchTo().window(list.get(0));
        driver.close();
    }
   

    @AfterMethod
    public void browserclose() {
        driver.quit();
        System.out.println("completed");
    }
}
